# wrangler.toml
name = "artilate" # Nombre de tu proyecto en Cloudflare Pages
compatibility_date = "2023-10-10" # Fecha de compatibilidad para Cloudflare Workers

# Configuraci칩n para archivos est치ticos (SSG)
pages_build_output_dir = "dist" # Carpeta donde est치n los archivos est치ticos generados

# Opcional: Comando para construir tu proyecto
[build]
command = "npm run build"