name = "artilate-workers"
compatibility_date = "2025-04-18"
main = "./dist/_worker.js/index.js" # Ajusta el nombre del archivo si es diferente

routes = [
  { pattern = "https://artilate.com/*", zone_id = "e8faa93bf68bfbe0a671e8909bdcb40f" }
]