# wrangler.toml
name = "artilate" # Nombre de tu proyecto en Cloudflare Pages
compatibility_date = "2023-10-10" # Fecha de compatibilidad para Cloudflare Workers

# Carpeta donde están los archivos estáticos generados
pages_build_output_dir = "dist"