# wrangler.toml
name = "artilate" # Nombre de tu proyecto en Cloudflare Pages
compatibility_date = "2023-10-10" # Fecha de compatibilidad para Cloudflare Workers

# Configuración para archivos estáticos (SSG)
[build]
command = "npm run build" # Comando para construir tu proyecto
upload = { format = "static", dir = "dist" } # Carpeta donde están los archivos estáticos

# Configuración para SSR (opcional)
[[pages]]
directory = "src/pages" # Carpeta de páginas si usas Astro