export const img = [
    { id: 1, img: '/assets/photo1.avif', description: 'A beautiful landscape with mountains and a clear sky.' },
    { id: 2, img: '/assets/photo2.avif', description: 'A serene beach with golden sand and turquoise water.' },
    { id: 3, img: '/assets/photo3.avif', description: 'A bustling cityscape at night with glowing lights.' },
    { id: 4, img: '/assets/photo4.avif', description: 'A dense forest with sunlight filtering through the trees.' },
    { id: 5, img: '/assets/photo5.avif', description: 'A close-up of a vibrant red flower in bloom.' },
    { id: 6, img: '/assets/photo6.avif', description: 'A snowy mountain peak under a bright blue sky.' },
    { id: 7, img: '/assets/photo7.avif', description: 'A calm lake reflecting the surrounding trees and sky.' },
    { id: 8, img: '/assets/photo8.avif', description: 'A colorful hot air balloon floating in the sky.' },
    { id: 9, img: '/assets/photo9.avif', description: 'A historic castle surrounded by lush greenery.' },
    { id: 10, img: '/assets/photo10.avif', description: 'A winding road through a picturesque countryside.' },
    { id: 11, img: '/assets/photo11.avif', description: 'A vibrant sunset over the ocean horizon.' },
    { id: 12, img: '/assets/photo12.avif', description: 'A charming village with cobblestone streets and old houses.' },
    { id: 13, img: '/assets/photo13.avif', description: 'A majestic waterfall cascading into a rocky pool.' },
    { id: 14, img: '/assets/photo14.avif', description: 'A field of sunflowers under a bright summer sky.' },
    { id: 15, img: '/assets/photo15.avif', description: 'A tranquil desert scene with rolling sand dunes.' },
    { id: 16, img: '/assets/photo16.avif', description: 'A misty morning in a dense forest.' },
    { id: 17, img: '/assets/photo17.avif', description: 'A vibrant coral reef teeming with marine life.' },
    { id: 18, img: '/assets/photo18.avif', description: 'A snowy village illuminated by warm lights.' },
    { id: 19, img: '/assets/photo19.avif', description: 'A dramatic cliffside overlooking the ocean.' },
    { id: 20, img: '/assets/photo20.avif', description: 'A peaceful meadow with wildflowers in bloom.' },
    { id: 21, img: '/assets/photo21.avif', description: 'A starry night sky over a quiet lake.' },
    { id: 22, img: '/assets/photo22.avif', description: 'A rustic barn surrounded by autumn foliage.' },
    { id: 23, img: '/assets/photo23.avif', description: 'A tropical island with palm trees and clear water.' },
    { id: 24, img: '/assets/photo24.avif', description: 'A panoramic view of a mountain range at sunrise.' },
];